name = "SimpleWorkflowRecipes"
uuid = "8a651d91-a9bf-46a9-bd79-85d5b70f63c4"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
EasyJobsBase = "db8ca866-b61f-4bd1-a9b9-75c107d645d4"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
